FROM skranz/repbox_mono:ejd

ARG STATA_LIC

RUN echo $STATA_LIC > /usr/local/stata/stata.lic

COPY io_config.yml /root/io_config.yml

# repbox_config.yml is dynamically generated by the process starting
# the GHA workflow
COPY config.yml /root/repbox_config.yml

MAINTAINER Sebastian Kranz "sebastian.kranz@uni-ulm.de"
